
FROM node:20-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

RUN npm install -g prisma

COPY . .

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
