import speakeasy from 'speakeasy';
import qrcode from 'qrcode';
import { config } from '@/config';

/**
 * Generates a secret for TOTP
 * @param email - User's email (displayed in the authenticator app)
 * @returns Generated secret with data for QR
 */
export function generateTOTPSecret(email: string) {
  const secret = speakeasy.generateSecret({
    name: `${config.twoFactor.issuer}:${email}`,
    issuer: config.twoFactor.issuer,
    length: 32,
  });

  return {
    secret: secret.base32, // This is what we store in the DB (encrypted)
    otpauthUrl: secret.otpauth_url || '', // URL to generate QR
  };
}

/**
 * Generates a QR code from an otpauth URL
 * @param otpauthUrl - otpauth URL generated by speakeasy
 * @returns QR code in data URL format (base64)
 */
export async function generateQRCode(otpauthUrl: string): Promise<string> {
  try {
    return await qrcode.toDataURL(otpauthUrl);
  } catch {
    throw new Error('Error generating QR code');
  }
}

/**
 * Validates a TOTP code
 * @param secret - Secret in base32 (unencrypted)
 * @param code - 6-digit code entered by the user
 * @returns true if the code is valid, false otherwise
 */
export function verifyTOTPCode(secret: string, code: string): boolean {
  return speakeasy.totp.verify({
    secret: secret,
    encoding: 'base32',
    token: code,
    window: 1, // Allow codes from 30 seconds before or after
  });
}

/**
 * Generates the current TOTP code (useful for testing)
 * @param secret - Secret in base32
 * @returns Current 6-digit code
 */
export function generateTOTPCode(secret: string): string {
  return speakeasy.totp({
    secret: secret,
    encoding: 'base32',
  });
}
